default_agent: mcp_server_agentic_core_why
agents:
  mcp_server_agentic_core_why:
    name: mcp_server_agentic_core_why
    entrypoint: /home/ec2-user/smus_agentic_core/agentic_core/code/mcp_agentic_core/mcp_server.py
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '476114117552'
      region: us-west-2
      ecr_repository: 476114117552.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-mcp_server_agentic_core_why
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
